export const englishLanguage = {
    playBigger: 'Play Bigger',
    manageCampaigns: 'Manage Campaigns',
    upcomingCampaigns: 'Upcoming Campaigns',
    liveCampaigns: 'Live Campaigns',
    pastCampaigns: 'Past Campaigns',
    date: 'DATE',
    campaign: 'CAMPAIGN',
    view: 'VIEW',
    actions: 'ACTIONS',
    viewPricing: 'View Pricing',
    report: 'Report',
    scheduleAgain: 'Schedule Again',
    daysAgo: 'Days Ago',
    daysAhead: 'Days Ahead',
    pricing: 'Pricing',
    week: 'Week',
    month: 'Month',
    months: 'Months',
    year: 'Year',
    close: 'Close'
};

export const germanLanguage = {
    playBigger: 'Spielen Sie größer',
    manageCampaigns: 'Kampagnen verwalten',
    upcomingCampaigns: 'Kommende Kampagnen',
    liveCampaigns: 'Live-Kampagnen',
    pastCampaigns: 'Vergangene Kampagnen',
    date: 'DATUM',
    campaign: 'KAMPAGNE',
    view: 'AUSSICHT',
    actions: 'AKTIONEN',
    viewPricing: 'Preise anzeigen',
    report: 'Bericht',
    scheduleAgain: 'Planen Sie erneut',
    daysAgo: 'Vor Tagen',
    daysAhead: 'Tage voraus',
    pricing: 'Preisgestaltung',
    week: 'Woche',
    month: 'Monat',
    months: 'Monate',
    year: 'Jahr',
    close: 'Schließen'
};